[package]
name = "crossterm"
version = "0.17.7"
authors = ["T. Post"]
description = "An crossplatform terminal library for manipulating terminals."
repository = "https://github.com/crossterm-rs/crossterm"
documentation = "https://docs.rs/crossterm/"
license = "MIT"
keywords = ["event", "color", "cli", "input", "terminal"]
exclude = ["target", "Cargo.lock"]
readme = "README.md"
edition = "2018"
categories = ["command-line-interface", "command-line-utilities"]

[lib]
name = "crossterm"
path = "src/lib.rs"

#
# Build documentation with all features -> EventStream is available
#
[package.metadata.docs.rs]
all-features = true

#
# Features
#
[features]
default = []
event-stream = ["futures-util"]

#
# Shared dependencies
#
[dependencies]
bitflags = "1.2"
lazy_static = "1.4"
futures-util = { version = "0.3", optional = true, default-features = false }
serde = { version = "1.0", features = ["derive"], optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
parking_lot = "0.10"

#
# Windows dependencies
#
[target.'cfg(windows)'.dependencies.winapi]
version = "0.3.8"
features = ["winuser"]

[target.'cfg(windows)'.dependencies]
crossterm_winapi = "0.6.1"

#
# UNIX dependencies
#
[target.'cfg(unix)'.dependencies]
libc = "0.2"
mio = {version="0.7", features=["os-poll"]}
signal-hook = { version = "0.1.15", features = ["mio-0_7-support"] }

#
# WASM dependencies
#
[target.'cfg(target_arch = "wasm32")'.dependencies]
xterm-js-sys = { version = "4.6.0-alpha0", features = ["crossterm-support"] }

#
# Dev dependencies (examples, ...)
#
[dev-dependencies]
tokio = { version = "0.2.11", features = ["full"] }
futures = "0.3"
futures-timer = "3.0"
async-std = "1.4"

[patch.crates-io]
wasm-bindgen = { git = "https://github.com/rrbutani/wasm-bindgen.git", branch = "patches" } # TODO: remove once things get merged!
xterm-js-sys = { git = "https://github.com/rrbutani/xterm-js-sys.git" } # TODO: remove!
